version: '3'
services:
  frontend:
    build:
      context: .
    command: ['/bin/sh', '-c', 'npm install --quiet; npm run dev']
    # command: ['/bin/sh', '-c', 'npm install --quiet; npm run build; npm run start']
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "80:8000"
    env_file:
      - .env