FROM node:10.16.0-alpine AS dependencies
RUN mkdir -p /usr/app
WORKDIR /usr/app

ENV NODE_ENV=production
ENV PORT=8000
ENV VAT=7
ARG SERVICE_URL

COPY package*.json ./
COPY ./ ./
RUN npm install
RUN npm run build

FROM nginx:1.17.2-alpine
WORKDIR /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d
COPY --from=dependencies /usr/app/dist ./

EXPOSE 80
